-- DROP SCHEMA comun;

CREATE SCHEMA comun AUTHORIZATION postgres;

-- DROP TABLE comun.usuario;

CREATE TABLE comun.usuario
(
    --campos
usua_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, --pk

usua_nombre varchar(150),
usua_email varchar(100),
usua_contrania varchar(500),
usua_staff boolean default false,
--

-- llave primaria
    CONSTRAINT usuario_pkey PRIMARY KEY (usua_id)
--
-- llaves foraneas
);

-- DROP SCHEMA inventario;

CREATE SCHEMA inventario AUTHORIZATION postgres;

-- DROP TABLE inventario.propiedad;

CREATE TABLE inventario.propiedad
(
    --campos
prop_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, --pk

prop_titulo varchar(150),
prop_descripcion varchar(1000),
prop_tipocasa varchar(1),
prop_precio numeric(20,0),
prop_ubicacion varchar(500),
prop_superficie numeric(20,0),
prop_numerohabitaciones numeric(20,0),
prop_numerobanios numeric(20,0),
usua_id bigint,
--

-- llave primaria
    CONSTRAINT propiedad_pkey PRIMARY KEY (prop_id),
--
-- llaves foraneas
    CONSTRAINT fk_propiedad_usuario FOREIGN KEY (usua_id)
        REFERENCES comun.usuario (usua_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- DROP TABLE inventario.propiedadimagen;

CREATE TABLE inventario.propiedadimagen
(
    --campos
prim_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, --pk

prim_filename varchar(2000),
prim_mimetype varchar(100),
prim_data BYTEA,
prop_id bigint,
--

-- llave primaria
    CONSTRAINT propiedadimagen_pkey PRIMARY KEY (prim_id),
--
-- llaves foraneas
    CONSTRAINT fk_propiedadimagen_propiedad FOREIGN KEY (prop_id)
        REFERENCES inventario.propiedad (prop_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

INSERT INTO comun.usuario
(usua_id, usua_nombre, usua_email, usua_contrania, usua_staff)
VALUES(0, 'admin', 'admin@admin.com', 'admin', true);